version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: datawarehouse_postgres
    environment:
      POSTGRES_DB: datawarehouse
      POSTGRES_USER: dwuser
      POSTGRES_PASSWORD: dwpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dw_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: datawarehouse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@datawarehouse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - dw_network

volumes:
  postgres_data:

networks:
  dw_network:
    driver: bridge 